# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vtk.proto',
  package='vtk',
  syntax='proto3',
  serialized_pb=_b('\n\tvtk.proto\x12\x03vtk\"\xff\x01\n\x06Record\x12%\n\ntrackpoint\x18\x01 \x01(\x0b\x32\x0f.vtk.TrackpointH\x00\x12&\n\x0btimer_event\x18\x02 \x01(\x0b\x32\x0f.vtk.TimerEventH\x00\x12(\n\x0c\x62utton_event\x18\x10 \x01(\x0b\x32\x10.vtk.ButtonEventH\x00\x12\x38\n\x14hardware_description\x18\x11 \x01(\x0b\x32\x18.vtk.HardwareDescriptionH\x00\x12\x38\n\x14magnetic_declination\x18\x12 \x01(\x0b\x32\x18.vtk.MagneticDeclinationH\x00\x42\x08\n\x06record\"\xb6\x01\n\nTrackpoint\x12\x0f\n\x07seconds\x18\x01 \x01(\r\x12\x14\n\x0c\x63\x65ntiseconds\x18\x02 \x01(\r\x12\x12\n\nlatitudeE7\x18\x03 \x01(\x11\x12\x13\n\x0blongitudeE7\x18\x04 \x01(\x11\x12\x13\n\x0bsog_knotsE1\x18\x05 \x01(\r\x12\x0b\n\x03\x63og\x18\x06 \x01(\r\x12\x0c\n\x04q1E3\x18\x07 \x01(\x11\x12\x0c\n\x04q2E3\x18\x08 \x01(\x11\x12\x0c\n\x04q3E3\x18\t \x01(\x11\x12\x0c\n\x04q4E3\x18\n \x01(\x11\"\xb6\x01\n\nTimerEvent\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.vtk.TimerEvent.TimerEventType\x12\x0f\n\x07seconds\x18\x02 \x01(\x05\"i\n\x0eTimerEventType\x12\x0e\n\nTIMER_NONE\x10\x00\x12\x11\n\rTIMER_STARTED\x10\x01\x12\x11\n\rTIMER_STOPPED\x10\x02\x12\x11\n\rTIMER_EXPIRED\x10\x03\x12\x0e\n\nTIMER_TICK\x10\x04\"\xa9\x01\n\x0b\x42uttonEvent\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .vtk.ButtonEvent.ButtonEventType\"j\n\x0f\x42uttonEventType\x12\x0f\n\x0b\x42UTTON_NONE\x10\x00\x12\r\n\tBUTTON_RC\x10\x01\x12\x0e\n\nBUTTON_PIN\x10\x02\x12\x17\n\x13\x42UTTON_LINE_CLEARED\x10\x03\x12\x0e\n\nBUTTON_MAX\x10\x04\"h\n\x13HardwareDescription\x12\x10\n\x08model_id\x18\x01 \x01(\x05\x12\x13\n\x0bhardware_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x66irmware_id\x18\x03 \x01(\x05\x12\x15\n\rserial_number\x18\x04 \x01(\x05\"*\n\x13MagneticDeclination\x12\x13\n\x0b\x64\x65\x63lination\x18\x01 \x01(\x11\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TIMEREVENT_TIMEREVENTTYPE = _descriptor.EnumDescriptor(
  name='TimerEventType',
  full_name='vtk.TimerEvent.TimerEventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TIMER_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMER_STARTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMER_STOPPED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMER_EXPIRED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMER_TICK', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=539,
  serialized_end=644,
)
_sym_db.RegisterEnumDescriptor(_TIMEREVENT_TIMEREVENTTYPE)

_BUTTONEVENT_BUTTONEVENTTYPE = _descriptor.EnumDescriptor(
  name='ButtonEventType',
  full_name='vtk.ButtonEvent.ButtonEventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUTTON_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUTTON_RC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUTTON_PIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUTTON_LINE_CLEARED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUTTON_MAX', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=710,
  serialized_end=816,
)
_sym_db.RegisterEnumDescriptor(_BUTTONEVENT_BUTTONEVENTTYPE)


_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='vtk.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackpoint', full_name='vtk.Record.trackpoint', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timer_event', full_name='vtk.Record.timer_event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='button_event', full_name='vtk.Record.button_event', index=2,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_description', full_name='vtk.Record.hardware_description', index=3,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='magnetic_declination', full_name='vtk.Record.magnetic_declination', index=4,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='record', full_name='vtk.Record.record',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=19,
  serialized_end=274,
)


_TRACKPOINT = _descriptor.Descriptor(
  name='Trackpoint',
  full_name='vtk.Trackpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='vtk.Trackpoint.seconds', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centiseconds', full_name='vtk.Trackpoint.centiseconds', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitudeE7', full_name='vtk.Trackpoint.latitudeE7', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitudeE7', full_name='vtk.Trackpoint.longitudeE7', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sog_knotsE1', full_name='vtk.Trackpoint.sog_knotsE1', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cog', full_name='vtk.Trackpoint.cog', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q1E3', full_name='vtk.Trackpoint.q1E3', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q2E3', full_name='vtk.Trackpoint.q2E3', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q3E3', full_name='vtk.Trackpoint.q3E3', index=8,
      number=9, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q4E3', full_name='vtk.Trackpoint.q4E3', index=9,
      number=10, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=459,
)


_TIMEREVENT = _descriptor.Descriptor(
  name='TimerEvent',
  full_name='vtk.TimerEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='vtk.TimerEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='vtk.TimerEvent.seconds', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TIMEREVENT_TIMEREVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=644,
)


_BUTTONEVENT = _descriptor.Descriptor(
  name='ButtonEvent',
  full_name='vtk.ButtonEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='vtk.ButtonEvent.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUTTONEVENT_BUTTONEVENTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=816,
)


_HARDWAREDESCRIPTION = _descriptor.Descriptor(
  name='HardwareDescription',
  full_name='vtk.HardwareDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='vtk.HardwareDescription.model_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hardware_id', full_name='vtk.HardwareDescription.hardware_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firmware_id', full_name='vtk.HardwareDescription.firmware_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='vtk.HardwareDescription.serial_number', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=818,
  serialized_end=922,
)


_MAGNETICDECLINATION = _descriptor.Descriptor(
  name='MagneticDeclination',
  full_name='vtk.MagneticDeclination',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='declination', full_name='vtk.MagneticDeclination.declination', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=924,
  serialized_end=966,
)

_RECORD.fields_by_name['trackpoint'].message_type = _TRACKPOINT
_RECORD.fields_by_name['timer_event'].message_type = _TIMEREVENT
_RECORD.fields_by_name['button_event'].message_type = _BUTTONEVENT
_RECORD.fields_by_name['hardware_description'].message_type = _HARDWAREDESCRIPTION
_RECORD.fields_by_name['magnetic_declination'].message_type = _MAGNETICDECLINATION
_RECORD.oneofs_by_name['record'].fields.append(
  _RECORD.fields_by_name['trackpoint'])
_RECORD.fields_by_name['trackpoint'].containing_oneof = _RECORD.oneofs_by_name['record']
_RECORD.oneofs_by_name['record'].fields.append(
  _RECORD.fields_by_name['timer_event'])
_RECORD.fields_by_name['timer_event'].containing_oneof = _RECORD.oneofs_by_name['record']
_RECORD.oneofs_by_name['record'].fields.append(
  _RECORD.fields_by_name['button_event'])
_RECORD.fields_by_name['button_event'].containing_oneof = _RECORD.oneofs_by_name['record']
_RECORD.oneofs_by_name['record'].fields.append(
  _RECORD.fields_by_name['hardware_description'])
_RECORD.fields_by_name['hardware_description'].containing_oneof = _RECORD.oneofs_by_name['record']
_RECORD.oneofs_by_name['record'].fields.append(
  _RECORD.fields_by_name['magnetic_declination'])
_RECORD.fields_by_name['magnetic_declination'].containing_oneof = _RECORD.oneofs_by_name['record']
_TIMEREVENT.fields_by_name['type'].enum_type = _TIMEREVENT_TIMEREVENTTYPE
_TIMEREVENT_TIMEREVENTTYPE.containing_type = _TIMEREVENT
_BUTTONEVENT.fields_by_name['type'].enum_type = _BUTTONEVENT_BUTTONEVENTTYPE
_BUTTONEVENT_BUTTONEVENTTYPE.containing_type = _BUTTONEVENT
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
DESCRIPTOR.message_types_by_name['Trackpoint'] = _TRACKPOINT
DESCRIPTOR.message_types_by_name['TimerEvent'] = _TIMEREVENT
DESCRIPTOR.message_types_by_name['ButtonEvent'] = _BUTTONEVENT
DESCRIPTOR.message_types_by_name['HardwareDescription'] = _HARDWAREDESCRIPTION
DESCRIPTOR.message_types_by_name['MagneticDeclination'] = _MAGNETICDECLINATION

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(
  DESCRIPTOR = _RECORD,
  __module__ = 'vtk_pb2'
  # @@protoc_insertion_point(class_scope:vtk.Record)
  ))
_sym_db.RegisterMessage(Record)

Trackpoint = _reflection.GeneratedProtocolMessageType('Trackpoint', (_message.Message,), dict(
  DESCRIPTOR = _TRACKPOINT,
  __module__ = 'vtk_pb2'
  # @@protoc_insertion_point(class_scope:vtk.Trackpoint)
  ))
_sym_db.RegisterMessage(Trackpoint)

TimerEvent = _reflection.GeneratedProtocolMessageType('TimerEvent', (_message.Message,), dict(
  DESCRIPTOR = _TIMEREVENT,
  __module__ = 'vtk_pb2'
  # @@protoc_insertion_point(class_scope:vtk.TimerEvent)
  ))
_sym_db.RegisterMessage(TimerEvent)

ButtonEvent = _reflection.GeneratedProtocolMessageType('ButtonEvent', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONEVENT,
  __module__ = 'vtk_pb2'
  # @@protoc_insertion_point(class_scope:vtk.ButtonEvent)
  ))
_sym_db.RegisterMessage(ButtonEvent)

HardwareDescription = _reflection.GeneratedProtocolMessageType('HardwareDescription', (_message.Message,), dict(
  DESCRIPTOR = _HARDWAREDESCRIPTION,
  __module__ = 'vtk_pb2'
  # @@protoc_insertion_point(class_scope:vtk.HardwareDescription)
  ))
_sym_db.RegisterMessage(HardwareDescription)

MagneticDeclination = _reflection.GeneratedProtocolMessageType('MagneticDeclination', (_message.Message,), dict(
  DESCRIPTOR = _MAGNETICDECLINATION,
  __module__ = 'vtk_pb2'
  # @@protoc_insertion_point(class_scope:vtk.MagneticDeclination)
  ))
_sym_db.RegisterMessage(MagneticDeclination)


# @@protoc_insertion_point(module_scope)
