# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvtk.proto\x12\x03vtk\"\xff\x01\n\x06Record\x12%\n\ntrackpoint\x18\x01 \x01(\x0b\x32\x0f.vtk.TrackpointH\x00\x12&\n\x0btimer_event\x18\x02 \x01(\x0b\x32\x0f.vtk.TimerEventH\x00\x12(\n\x0c\x62utton_event\x18\x10 \x01(\x0b\x32\x10.vtk.ButtonEventH\x00\x12\x38\n\x14hardware_description\x18\x11 \x01(\x0b\x32\x18.vtk.HardwareDescriptionH\x00\x12\x38\n\x14magnetic_declination\x18\x12 \x01(\x0b\x32\x18.vtk.MagneticDeclinationH\x00\x42\x08\n\x06record\"\xb6\x01\n\nTrackpoint\x12\x0f\n\x07seconds\x18\x01 \x01(\r\x12\x14\n\x0c\x63\x65ntiseconds\x18\x02 \x01(\r\x12\x12\n\nlatitudeE7\x18\x03 \x01(\x11\x12\x13\n\x0blongitudeE7\x18\x04 \x01(\x11\x12\x13\n\x0bsog_knotsE1\x18\x05 \x01(\r\x12\x0b\n\x03\x63og\x18\x06 \x01(\r\x12\x0c\n\x04q1E3\x18\x07 \x01(\x11\x12\x0c\n\x04q2E3\x18\x08 \x01(\x11\x12\x0c\n\x04q3E3\x18\t \x01(\x11\x12\x0c\n\x04q4E3\x18\n \x01(\x11\"\xb6\x01\n\nTimerEvent\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.vtk.TimerEvent.TimerEventType\x12\x0f\n\x07seconds\x18\x02 \x01(\x05\"i\n\x0eTimerEventType\x12\x0e\n\nTIMER_NONE\x10\x00\x12\x11\n\rTIMER_STARTED\x10\x01\x12\x11\n\rTIMER_STOPPED\x10\x02\x12\x11\n\rTIMER_EXPIRED\x10\x03\x12\x0e\n\nTIMER_TICK\x10\x04\"\xa9\x01\n\x0b\x42uttonEvent\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .vtk.ButtonEvent.ButtonEventType\"j\n\x0f\x42uttonEventType\x12\x0f\n\x0b\x42UTTON_NONE\x10\x00\x12\r\n\tBUTTON_RC\x10\x01\x12\x0e\n\nBUTTON_PIN\x10\x02\x12\x17\n\x13\x42UTTON_LINE_CLEARED\x10\x03\x12\x0e\n\nBUTTON_MAX\x10\x04\"h\n\x13HardwareDescription\x12\x10\n\x08model_id\x18\x01 \x01(\x05\x12\x13\n\x0bhardware_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x66irmware_id\x18\x03 \x01(\x05\x12\x15\n\rserial_number\x18\x04 \x01(\x05\"*\n\x13MagneticDeclination\x12\x13\n\x0b\x64\x65\x63lination\x18\x01 \x01(\x11\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vtk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORD._serialized_start=19
  _RECORD._serialized_end=274
  _TRACKPOINT._serialized_start=277
  _TRACKPOINT._serialized_end=459
  _TIMEREVENT._serialized_start=462
  _TIMEREVENT._serialized_end=644
  _TIMEREVENT_TIMEREVENTTYPE._serialized_start=539
  _TIMEREVENT_TIMEREVENTTYPE._serialized_end=644
  _BUTTONEVENT._serialized_start=647
  _BUTTONEVENT._serialized_end=816
  _BUTTONEVENT_BUTTONEVENTTYPE._serialized_start=710
  _BUTTONEVENT_BUTTONEVENTTYPE._serialized_end=816
  _HARDWAREDESCRIPTION._serialized_start=818
  _HARDWAREDESCRIPTION._serialized_end=922
  _MAGNETICDECLINATION._serialized_start=924
  _MAGNETICDECLINATION._serialized_end=966
# @@protoc_insertion_point(module_scope)
